### ISSUE TITLE
No association of a row and the cells that are placed in it.

### ISSUE THREAD

**Issue by ahmednofal** [RsynTeam/rsyn-x#13]
As an example of the problem, to check legality In the file x/misc/iccad2015_evaluate_solution_0831/check_legality.cpp, testing for legality type 4 should be using an association of rows, sites and the cells placed in them. For instance the physicalrows in the physicaldesign class can have a method that returns the cells placed in that row.

**Comment by gaflach** [comment]
Hi, Ahmad.

It seems this is too specific to be part of the core infrastructure and can impose an overhead (e.g. keeping this up-to-date) even when it is not necessary. And it's not clear what to do when the design is not in a legalized state (i.e. cells not aligned to rows).

This should be handled by a service similar to what the Jezz legalizer does.
Jezz provides APIs to legalize, find white spaces, etc.
I don't think Jezz already exposes an API to traverse cells in a particular row, but you can add that.

You can take a look at the class Jezz::NodeCollection.
Right now it is used to traverse all nodes in all rows, but you can change it to work only on one particular row.
https://github.com/RsynTeam/rsyn-x/blob/master/x/src/x/jezz/Jezz.h#L816

**Comment by ahmednofal** [comment]
The association would be an addition; whoever not wanting to abide by it can go back to mere bounds and DBU points, right ? There is no need to always keep it up to date, the responsibility of keeping the array up to day falls entirely on whoever is developing the placement algorithm which has nothing to do with the Rsyn framework. am I correct ?
