### ISSUE TITLE
No way to set the placement of a port or generally a pin

### ISSUE THREAD

**Issue by ahmednofal** [RsynTeam/rsyn-x#14]
The PhysicalDesign class does not offer any way to set the placement of the ports or the pins. For the ports and the pins to have placement information they can only be extracted from the supplied def files. Because the interface is highly enforced through privatizing PhysicalDesign class methods and Protecting them, the only way is to add a method to PhysicalDesign itself that does the placement of the pins, which is really really bad to do, and still makes the algorithm for placement quite static which is the opposite of what Rsyn is made for.

**Comment by ahmednofal** [comment]
Actually there could be added a placePort which is very similar to placeCell.

**Comment by eder-matheus** [comment]
Hi, Ahmed.

Fixed #`173b91f`
