### ISSUE TITLE
error when make

### ISSUE THREAD

**Issue by ghostyyp** [RsynTeam/rsyn-x#15]
I tried the following process  in Ubuntu 16.04.5 LST  with g++ 5.4.0，

> $ git clone https://github.com/rsyn/rsyn-x.git
> $ cd rsyn-x
> $ mkdir build 
> $ cd build
> $ cmake ..
> $ make
 
but i got a error when make:

/usr/include/boost/polygon/detail/rectangle_formation.hpp: In instantiation of ‘void boost::polygon::form_rectangles(output_container&, iterator_type, iterator_type, boost::polygon::orientation_2d, rectangle_concept) [with output_container = std::vector<boost::polygon::rectangle_data<double> >; iterator_type = __gnu_cxx::__normal_iterator<std::pair<double, std::pair<double, int> >*, std::vector<std::pair<double, std::pair<double, int> >, std::allocator<std::pair<double, std::pair<double, int> > > > >; rectangle_concept = boost::polygon::rectangle_concept]’:
/usr/include/boost/polygon/polygon_90_set_data.hpp:180:22:   required from ‘void boost::polygon::polygon_90_set_data<T>::get_rectangles(output_container&) const [with output_container = std::vector<boost::polygon::rectangle_data<double> >; T = double]’
/usr/include/boost/polygon/polygon_90_set_concept.hpp:86:5:   required from ‘typename boost::enable_if<typename boost::polygon::gtl_if<typename boost::polygon::is_polygon_90_set_type<polygon_set_type_2>::type>::type, void>::type boost::polygon::get_rectangles(output_container_type&, const polygon_set_type&) [with output_container_type = std::vector<boost::polygon::rectangle_data<double> >; polygon_set_type = boost::polygon::polygon_90_with_holes_data<double>; typename boost::enable_if<typename boost::polygon::gtl_if<typename boost::polygon::is_polygon_90_set_type<polygon_set_type_2>::type>::type, void>::type = void]’
/rsyn/rsyn-x/rsyn/src/rsyn/io/parser/lef_def/LEFControlParser.cpp:270:53:   required from here
/usr/include/boost/polygon/detail/rectangle_formation.hpp:261:13: **error**: no matching function for call to ‘abs(int&)’
       if(abs((*itr).second.second) > 1) itr = tmp_itr; //next edge begins from this vertex
             ^
In file included from /usr/include/boost/geometry/policies/robustness/segment_ratio.hpp:14:0,
                 from /usr/include/boost/geometry/policies/robustness/no_rescale_policy.hpp:19,
                 from /usr/include/boost/geometry/algorithms/detail/overlay/get_turn_info_helpers.hpp:17,
                 from /usr/include/boost/geometry/algorithms/detail/overlay/get_turn_info.hpp:31,
                 from /usr/include/boost/geometry/algorithms/detail/overlay/get_turns.hpp:59,
                 from /usr/include/boost/geometry/algorithms/within.hpp:56,
                 from /usr/include/boost/geometry/algorithms/covered_by.hpp:30,
                 from /usr/include/boost/geometry/algorithms/detail/disjoint/areal_areal.hpp:26,
                 from /usr/include/boost/geometry/algorithms/detail/disjoint/implementation.hpp:25,
                 from /usr/include/boost/geometry/algorithms/disjoint.hpp:25,
                 from /usr/include/boost/geometry/io/wkt/write.hpp:31,
                 from /usr/include/boost/geometry/io/wkt/wkt.hpp:18,
                 from /usr/include/boost/geometry/strategies/cartesian/buffer_end_round.hpp:20,
                 from /usr/include/boost/geometry/strategies/strategies.hpp:39,
                 from /usr/include/boost/geometry/geometry.hpp:50,
                 from /usr/include/boost/geometry.hpp:17,
                 from /rsyn/rsyn-x/rsyn/src/rsyn/io/parser/lef_def/LEFControlParser.cpp:39:

I could not find any solution on the internet, can you figure me out of this? Thanks very much.

**Comment by ghostyyp** [comment]
@RsynTeam @ahmednofal @chengengjie @gaflach @jucemarmonteiro 
Did any of you have encountered this problem?

**Comment by ghostyyp** [comment]
There are the lines i get from cmake:

root@ubuntu:/rsyn/rsyn-x/build# cmake ..
-- Rsyn
-- /rsyn/rsyn-x
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   system
--   filesystem
--   program_options
-- Configuring done
-- Generating done
-- Build files have been written to: /rsyn/rsyn-x/build

**Comment by ghostyyp** [comment]
The ubuntu i use is ubuntu-16.04.5-desktop-amd64

**Comment by gaflach** [comment]
In /rsyn/rsyn-x/rsyn/src/rsyn/io/parser/lef_def/LEFControlParser.cpp, replace

#include <boost/geometry.hpp>
#include <boost/geometry/geometries/adapted/boost_polygon.hpp>
#include <boost/geometry/algorithms/correct.hpp>

by

#define BOOST_POLYGON_NO_DEPS
#include <boost/polygon/polygon.hpp>

We'll try to check a fix in soon, one that covers both Ubuntu versions.

**Comment by ghostyyp** [comment]
Hi @gaflach 
Thank you so much. I really appreciate your replication.
Several hours ago, I re-installed ubunt 18.04 in vmware, and it seems the error just disappeared while making Rsyn.

Thanks again.

**Comment by ghostyyp** [comment]
@gaflach 
By the way, how much mem do i have to get to run rsyn? because  i got Segmentation fault (core dumped)
when i tried to open x/demo/simple/simple.rsyn.

**Comment by hplacido** [comment]
Hi @ghostyyp 

Probably the run directory hasn't been specified in the project properties. So a segmentation fault occurs since the POWV9.dat and PORT9.dat files can not be found.

To solve this issue, open the project properties in netbeans and select Run. Then, in the Run Directory field, type ../../run

Also, please make sure that in the Run command field the option -gui rsyn is present.

**Comment by ghostyyp** [comment]
Hi @hplacido 

Got it. 
it works now. 
Thanks.
