### ISSUE TITLE
ERROR:ld returned 1 exit status

### ISSUE THREAD

**Issue by liumengbjut** [RsynTeam/rsyn-x#2]
![_20180103173748](https://user-images.githubusercontent.com/18281699/34515398-df920b06-f0ac-11e7-9030-cca4920a6c12.png)

I met above problem.

**Comment by gaflach** [comment]
Hello.

What's your system?

**Comment by liumengbjut** [comment]
![_20180104094249](https://user-images.githubusercontent.com/18281699/34547106-adcf6a28-f133-11e7-80b7-e7b39a856240.png)
This is my ubuntu version

**Comment by gaflach** [comment]
Could you try to compile the lef/def parsers in your machine and then
replace liblef.a and libdef.a in /rsyn-x/rsyn/lib/linux?

https://www.dropbox.com/s/u51nm2xk1juaiav/lefdef-source-5.8.zip?dl=0

**Comment by jucemarmonteiro** [comment]
Hi, 

probably this error is caused by boost library version between ubuntu 14.04 and 16.04. Rsyn is developed in Ubuntu 16.04. Moreover, I had a similar problem when I tried to compile Rsyn in Centos 6. 

Jucemar
