### ISSUE TITLE
NetBeans crashes while building Rsyn-x project

### ISSUE THREAD

**Issue by konsmall** [RsynTeam/rsyn-x#22]
Net Beans crashes while building the Rsyn-x project that comes with the rsyn-x files. The IDE will get stuck at [  7%] of the building process, but not on the same file:
`[  7%] Building CXX object CMakeFiles/rsyn.dir/rsyn/src/rsyn/model/routing/DefaultRoutingEstimationModel.cpp.o`
`[  7%] Building CXX object CMakeFiles/rsyn.dir/rsyn/src/rsyn/model/congestion/DensityGrid/DensityGrid.cpp.o`
`[  7%] Building CXX object CMakeFiles/rsyn.dir/rsyn/src/rsyn/model/timing/Timer.cpp.o`

After a while the computer becomes completely unresponsive and i have to restart it

**Comment by cgkantidis** [comment]
Have you tried building outside NetBeans, from the terminal?
Also, how many parallel threads do you spawn for compilation? (It's the -j option after the make command).

**Comment by jucemarmonteiro** [comment]
I had a similar issue when I tried to compile in netbeans and in terminal with _make -j_. The memory of my computer was full and the computer was very slow. 
Can you monitor the memory use. You can also limit the number of parallel compiling threads to the number of processors on your computer (_make -j <numProc>_).

**Comment by konsmall** [comment]
Thank you for your responses! Truth is i just started using Ubuntu, how can i compile a whole Net Beans project from the terminal?

**Comment by cgkantidis** [comment]
Netbeans is an IDE (Integrated Development Environment), i.e. an editor where you write code. You don't need Netbeans to compile rsyn-x or contribute to it, you can use whatever editor you like.

To build the project outside an IDE, open the terminal and navigate to the directory with the rsyn code, it's the directory containing the CMakeLists.txt file, and do the following.
```
mkdir build
cd build
cmake ..
make -j 4
```

**Comment by konsmall** [comment]
Thank you for replying quickly, turns out i was able to build the project with the terminal, i had already done it, i just didn't understand what you were asking, sorry. I used the getting started and create a helloworld process guides.

I just rebuilt the project with your commands and had no problem. The problem remains with Netbeans IDE.

**Comment by jucemarmonteiro** [comment]
To configure -j 4 in netbeans:
- tools -> options -> C/C++ -> Project Options. 
In _Make Options:_  -j 4 

please find below a screen shoot 
![Screenshot from 2019-11-11 18-42-22](https://user-images.githubusercontent.com/23533447/68637392-57633d00-04b3-11ea-821c-091d524e82e5.png)

**Comment by konsmall** [comment]
Thanks for the help! I was actually able to make it work, although it was a bit slow. I changed the make command from the Project Properties -> Build -> Make -> Build Command and removed the 
"-j 8" that was there

![123](https://user-images.githubusercontent.com/57601522/68695396-9e206800-0583-11ea-9280-a4b07f5a0edb.png)

**Comment by cgkantidis** [comment]
Feel free to close the issue if you consider it fixed.

> Thanks for the help! I was actually able to make it work, although it was a bit slow. I changed the make command from the Project Properties -> Build -> Make -> Build Command and removed the
> "-j 8" that was there
> 
> ![123](https://user-images.githubusercontent.com/57601522/68695396-9e206800-0583-11ea-9280-a4b07f5a0edb.png)
