### ISSUE TITLE
Bug in mergeBounds with ispd2018 benchmarks

### ISSUE THREAD

**Issue by chengengjie** [RsynTeam/rsyn-x#8]
In `rsyn/io/reader/ISPD2018Reader.cpp`, there is `physicalDesignConfiguration["clsEnableMergeRectangles"] = true`. It invokes `mergeBounds` in `PhysicalDesign::addPhysicalLibraryCell` during reading obstacles. Bugs are triggered here. 

**Hint**
For example, for the cell type `BUFX2` in `ispd18_test5.input.lef`, the obstacles are:
```
OBS
    LAYER Metal1 ;
    RECT  0.04 0.14 0.17 0.23 ;
    RECT  0.04 0.72 0.36 0.78 ;
    RECT  0.04 0.14 0.09 1.04 ;
    RECT  0.31 0.49 0.36 0.78 ;
END
```
Before `mergeBounds`, they are (in DBU):
```
[(80, 280), (340, 460)]
[(80, 1440), (720, 1560)]
[(80, 280), (180, 2080)]
[(620, 980), (720, 1560)]
```
After `mergeBounds`, they are:
```
[(80, 280), (180, 460)]
[(180, 280), (340, 460)]
[(340, 1440), (620, 1560)]
[(620, 1440), (720, 1560)]
[(620, 980), (720, 1560)]
```

**Comment by gaflach** [comment]
Thanks for letting us know...
We'll work on it soon.

**Comment by eder-matheus** [comment]
Hi.

Thanks for catching this issue. `mergeBounds` function works only with the circuits of ICCAD15 so we are disabling this function by default in all readers, except in the ICCAD15 reader.
