### ISSUE TITLE
Flip cell/instance

### ISSUE THREAD

**Issue by cgkantidis** [RsynTeam/rsyn-x#9]
Is there any way to flip a cell by the X or Y axis?

I need this to align the VSS and VDD pins of cells, to the same tracks on the chip.

The `Instance` class, and more specifically the `InstanceData` class, has a member variable `PhysicalOrientation` called `clsOrientation`, but it's initialized to `ORIENTATION_INVALID`, and as far as I can see, it's changed nowhere.

If I create a setter for this member variable, and initialize it to `PhysicalOrientation::ORIENTATION_N`, and then change the orientation whenever I want to flip the Cell, is there any way to reflect this change in the physical design and to the final def file?

**Comment by jucemarmonteiro** [comment]
Hi, 

I  have added two methods to set and flip cell orientation. Please see setCellOrientation and flipCell. I also have added orientation parameter in the placeCell methods. 

Regards, 
Jucemar
